version: '3'
services:
  liferay:
    image: localhost:5000/liferay
    container_name: liferay
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - liferay_swarm
    ports:
     - "8080:8080"
    environment:
     - VIRTUAL_HOST=liferay.geko
     - VIRTUAL_PORT=8080
    links:
      - percona
      - elastic

  percona:
    image: localhost:5000/percona
    container_name: percona
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - liferay_swarm
    env_file:
      - percona.env
      
  elastic:
    image: localhost:5000/percona
    container_name: elasticsearch
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - liferay_swarm
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - VIRTUAL_HOST=elastic.geko
      - VIRTUAL_PORT=9200
    env_file:
      - elasticsearch/elasticsearch.env
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    links:
      - liferay
    networks:
      - liferay_swarm

networks:
  liferay_swarm:
    ipam:
      driver: "overlay"
      config:
        - subnet: 10.0.9.0/24
    
