version: '2'
services:
  web:
    build: .
    container_name: liferay7
    ports:
     - "8080:8080"
    environment:
     - VIRTUAL_HOST=liferay.geko
     - VIRTUAL_PORT=8080
    depends_on:
      - percona
      - elastic

  percona:
    image: "percona:latest"
    container_name: percona
    env_file:
      - percona.env
      
  elastic:
    build: elasticsearch/.
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - VIRTUAL_HOST=elastic.geko
      - VIRTUAL_PORT=9200
    env_file:
      - elasticsearch/elasticsearch.env
  
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    depends_on:
      - web