version: '2'
services:
  web:
    build: .
    ports:
     - "58080:8080"
    depends_on:
      - percona
      - elastic

  percona:
    image: "percona:latest"
    env_file:
      - percona.env
      
  elastic:
    build: elasticsearch/.
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - elasticsearch/elasticsearch.env
  
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/liferay.template
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
     - NGINX_HOST=liferay.geko
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/liferay.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"